// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PIForIILinkNext p i for i i link next
//
// swagger:model PIForIILinkNext
type PIForIILinkNext struct {

	// A link to the next collection starting at the supplied offset plus the supplied limit.
	// Example: https://api.cybersource.com/tms/v1/instrumentidentifiers/5B32CE6167B09343E05333B9D30A53E1/paymentinstruments?offset=25\u0026limit=5
	Href string `json:"href,omitempty"`
}

// Validate validates this p i for i i link next
func (m *PIForIILinkNext) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this p i for i i link next based on context it is used
func (m *PIForIILinkNext) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PIForIILinkNext) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PIForIILinkNext) UnmarshalBinary(b []byte) error {
	var res PIForIILinkNext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
